# Generated by Django 3.2.5 on 2021-12-21 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tesisler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCADA_KODU', models.CharField(max_length=50, verbose_name='Scada Kodu ')),
                ('ILCE', models.CharField(choices=[('İZMİT', 'İZMİT'), ('GEBZE', 'GEBZE'), ('ÇAYIROVA', 'ÇAYIROVA'), ('DİLOVASI', 'DİLOVASI'), ('DARICA', 'DARICA'), ('KÖRFEZ', 'KÖRFEZ'), ('DERİNCE', 'DERİNCE'), ('KANDIRA', 'KANDIRA'), ('BAŞİSKELE', 'BAŞİSKELE'), ('KARTEPE', 'KARTEPE'), ('GÖLCÜK', 'GÖLCÜK'), ('KARAMÜRSEL', 'KARAMÜRSEL')], max_length=50, verbose_name='İlçe ')),
                ('TESIS_ADI', models.CharField(max_length=100, verbose_name='Tesis Adı ')),
                ('TESIS_TIPI', models.CharField(choices=[('AAT', 'AAT'), ('İAT', 'İAT'), ('ATM', 'ATM'), ('İTMDP', 'İTMDP'), ('YTM', 'YTM'), ('HES', 'HES'), ('İBS', 'İBS'), ('DİĞER', 'DİĞER')], max_length=50, verbose_name='Tesis Tipi ')),
                ('KONUM', models.CharField(max_length=50, verbose_name='Konumu ')),
                ('OLUSTURMA_TARIHI', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan ')),
            ],
            options={
                'verbose_name': 'Tesis',
                'verbose_name_plural': 'Tesisler',
            },
        ),
        migrations.CreateModel(
            name='Jeneratorler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OLUSTURMA_TARIHI', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('PLAKA', models.CharField(max_length=50, verbose_name='Plaka ')),
                ('GUC', models.CharField(max_length=50, verbose_name='Gücü ')),
                ('MARKA', models.CharField(max_length=50, verbose_name='Marka  ')),
                ('MODEL', models.CharField(max_length=50, verbose_name='Model  ')),
                ('MOTOR_MARKA', models.CharField(blank=True, max_length=50, verbose_name='Motor Markası  ')),
                ('MOTOR_MODEL', models.CharField(blank=True, max_length=50, verbose_name='Motor Modeli  ')),
                ('MOTOR_SERINO', models.CharField(blank=True, max_length=50, verbose_name='Motor SeriNo  ')),
                ('ALT_MARKA', models.CharField(blank=True, max_length=50, verbose_name='Alternatör Markası  ')),
                ('ALT_MODEL', models.CharField(blank=True, max_length=50, verbose_name='Alternatör Modeli  ')),
                ('ALT_SERINO', models.CharField(blank=True, max_length=50, verbose_name='Alternatör SeriNo  ')),
                ('KABIN', models.CharField(blank=True, max_length=50, verbose_name='Kabin Durumu  ')),
                ('ALIS_YONTEMI', models.CharField(blank=True, max_length=50, verbose_name='Alış Yöntemi  ')),
                ('ACIKLAMA', models.TextField(blank=True, verbose_name='Açıklama  ')),
                ('TESIS', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='jenerator.tesisler', verbose_name='Tesis adı ')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan ')),
            ],
            options={
                'verbose_name': 'Jeneratör',
                'verbose_name_plural': 'Jeneratörler',
            },
        ),
        migrations.CreateModel(
            name='Arizalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ARIZA_TARIHI', models.DateTimeField(auto_now_add=True, verbose_name='Arıza Tarihi')),
                ('ARIZA_TIPI', models.CharField(choices=[('MOTOR İÇİ ARIZALARI', 'MOTOR İÇİ ARIZALARI'), ('ENJEKTÖR ARIZASI', 'ENJEKTÖR ARIZASI'), ('MOTOR KAYIŞI ARIZALARI', 'MOTOR KAYIŞI ARIZALARI'), ('HARARET ARIZASI', 'HARARET ARIZASI'), ('SU DEVİRDAİM ARIZASI', 'SU DEVİRDAİM ARIZASI'), ('TURBO ARIZASI', 'TURBO ARIZASI'), ('TURBO HORTUMU VE AKSAMI ARIZASI', 'TURBO HORTUMU VE AKSAMI ARIZASI'), ('YAKIT POMPASI ARIZASI', 'YAKIT POMPASI ARIZASI'), ('YAKIT HORTUMU ARIZASI', 'YAKIT HORTUMU ARIZASI'), ('YAKIT FİLTRE ARIZASI', 'YAKIT FİLTRE ARIZASI'), ('YAKIT YOK ARIZASI', 'YAKIT YOK ARIZASI'), ('YAKIT KÖTÜ ARIZASI', 'YAKIT KÖTÜ ARIZASI'), ('YAĞ HORTUMU ARIZASI', 'YAĞ HORTUMU ARIZASI'), ('YAĞ FİLTRE ARIZASI', 'YAĞ FİLTRE ARIZASI'), ('YAĞ SEVİYE ARIZASI', 'YAĞ SEVİYE ARIZASI'), ('HAVA FİLTRE ARIZASI', 'HAVA FİLTRE ARIZASI'), ('HAVA SİRKÜLASYON ARIZASI', 'HAVA SİRKÜLASYON ARIZASI'), ('RADYATÖR ARIZASI', 'RADYATÖR ARIZASI'), ('SU EKSİK ARIZASI', 'SU EKSİK ARIZASI'), ('SU FİLTRE ARIZASI', 'SU FİLTRE ARIZASI'), ('HİDROLİK GOVERNÖR ARIZASI', 'HİDROLİK GOVERNÖR ARIZASI'), ('DİĞER MOTOR ARIZASI', 'DİĞER MOTOR ARIZASI'), ('OTOMATİK KAYIŞ GERGİ TERTİBATI', 'OTOMATİK KAYIŞ GERGİ TERTİBATI'), ('MAGNETİK PİCK-UP ARIZASI', 'MAGNETİK PİCK-UP ARIZASI'), ('AKÜ ARIZASI', 'AKÜ ARIZASI'), ('ATEŞLEME ARIZASI', 'ATEŞLEME ARIZASI'), ('DÜŞÜK - YÜKSEK FREKANS ARIZASI', 'DÜŞÜK - YÜKSEK FREKANS ARIZASI'), ('AŞIRI YÜKLENME ARIZASI', 'AŞIRI YÜKLENME ARIZASI'), ('DÜŞÜK- YÜKSEK GERİLİM ARIZASI', 'DÜŞÜK- YÜKSEK GERİLİM ARIZASI'), ('ŞARJ DİNAMOSU ARIZASI', 'ŞARJ DİNAMOSU ARIZASI'), ('REDRESÖR ARIZASI', 'REDRESÖR ARIZASI'), ('YAKIT SEVİYE SENSÖRÜ ARIZASI', 'YAKIT SEVİYE SENSÖRÜ ARIZASI'), ('ALTERNATÖR SARGI ARIZASI', 'ALTERNATÖR SARGI ARIZASI'), ('ALTERNATÖR ARIZASI DİĞER', 'ALTERNATÖR ARIZASI DİĞER'), ('GOVERNÖR ARIZASI', 'GOVERNÖR ARIZASI'), ('GERİLİM DÜZENLEYİCİ ARIZASI', 'GERİLİM DÜZENLEYİCİ ARIZASI'), ('DÖNER DİYOT ARIZASI', 'DÖNER DİYOT ARIZASI'), ('MARŞ MOTORU ARIZASI', 'MARŞ MOTORU ARIZASI'), ('AKIM TRAFOSU ARIZASI', 'AKIM TRAFOSU ARIZASI'), ('REZİSTANS ARIZASI', 'REZİSTANS ARIZASI'), ('TERMOSTAT ARIZASI', 'TERMOSTAT ARIZASI'), ('MARŞ RÖLESİ ARIZASI', 'MARŞ RÖLESİ ARIZASI'), ('KONJEKTÖR ARIZASI', 'KONJEKTÖR ARIZASI'), ('BLOK SUYU ISITICISI ARIZASI', 'BLOK SUYU ISITICISI ARIZASI'), ('KONTROL KARTI ARIZASI', 'KONTROL KARTI ARIZASI'), ('ECU ARIZASI', 'ECU ARIZASI'), ('KUMANDA RÖLE VE SİGORTA ARIZASI', 'KUMANDA RÖLE VE SİGORTA ARIZASI'), ('KABLO TEMASSIZLIK ARIZASI', 'KABLO TEMASSIZLIK ARIZASI'), ('HARMONİK BOZULUM ARIZASI', 'HARMONİK BOZULUM ARIZASI'), ('ISITICI HORTUMU ARIZASI', 'ISITICI HORTUMU ARIZASI'), ('VOLAN DİŞLİSİ ARIZASI', 'VOLAN DİŞLİSİ ARIZASI'), ('KAYIŞ ARIZASI', 'KAYIŞ ARIZASI'), ('KABİN ARIZASI', 'KABİN ARIZASI'), ('TAHRİBAT ARIZASI', 'TAHRİBAT ARIZASI'), ('ÇALINMA', 'ÇALINMA'), ('SUSTURUCU VE EGZOS ARIZASI', 'SUSTURUCU VE EGZOS ARIZASI'), ('EMME VE EGZOS MANİFOLT ARIZASI', 'EMME VE EGZOS MANİFOLT ARIZASI'), ('YAĞ SOĞUTUCUSU ARIZASI', 'YAĞ SOĞUTUCUSU ARIZASI'), ('JENERATÖR AYLIK RUTİN BAKIM', 'JENERATÖR AYLIK RUTİN BAKIM'), ('JENERATÖR YILLIK RUTİN BAKIM', 'JENERATÖR YILLIK RUTİN BAKIM'), ('ELEKTRİK BİRİMİ İLE İLGİ İLGİLİ ARIZA', 'ELEKTRİK BİRİMİ İLE İLGİ İLGİLİ ARIZA'), ('SCADA KAYNAKLI ARIZA ', 'SCADA KAYNAKLI ARIZA ')], max_length=150, verbose_name='Arıza Tipi ')),
                ('DEGISEN_PARCA', models.CharField(blank=True, max_length=100, verbose_name='Değişen Parça  ')),
                ('ACIKLAMA', models.TextField(blank=True, verbose_name='Açıklama  ')),
                ('JENERATOR', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='jenerator.jeneratorler', verbose_name='Jenerator Plakası ')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan ')),
            ],
            options={
                'verbose_name': 'Arıza',
                'verbose_name_plural': 'Arızalar',
            },
        ),
    ]
