# Generated by Django 3.2.5 on 2021-12-24 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jenerator', '0002_auto_20211223_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periyodik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PERIYODIK_TARIHI', models.DateTimeField(auto_now_add=True, verbose_name='Bakım Tarihi')),
                ('PERSONEL', models.CharField(blank=True, max_length=50, verbose_name='Personel')),
                ('ACIKLAMA', models.TextField(blank=True, verbose_name='Açıklama  ')),
                ('JENERATOR', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jenerator.jeneratorler', verbose_name='Jenerator ')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan ')),
            ],
            options={
                'verbose_name': 'Periyodik Bakım',
                'verbose_name_plural': 'Periyodik Bakımlar',
            },
        ),
        migrations.CreateModel(
            name='FiltreliBakim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FBAKIM_TARIHI', models.DateTimeField(auto_now_add=True, verbose_name='Bakım Tarihi')),
                ('MOTORYAG', models.IntegerField(blank=True, verbose_name='Motor Yağı Miktarı ')),
                ('SOGSIVI', models.IntegerField(blank=True, verbose_name='Soğutma Sıvısı Miktarı ')),
                ('HAVAFILTRE', models.IntegerField(blank=True, verbose_name='Hava Filtresi ')),
                ('YAKITFILTRE', models.IntegerField(blank=True, verbose_name='Yakıt Filtresi ')),
                ('YAGFILTRE', models.IntegerField(blank=True, verbose_name='Yağ Filtresi ')),
                ('SUFILTRE', models.IntegerField(blank=True, verbose_name='Su Filtresi ')),
                ('PERSONEL', models.CharField(blank=True, max_length=50, verbose_name='Personel')),
                ('ACIKLAMA', models.TextField(blank=True, verbose_name='Açıklama  ')),
                ('JENERATOR', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jenerator.jeneratorler', verbose_name='Jenerator ')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan ')),
            ],
            options={
                'verbose_name': 'Filtreli Bakım',
                'verbose_name_plural': 'Filtreli Bakımlar',
            },
        ),
    ]
