# Generated by Django 3.2.5 on 2021-12-24 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jenerator', '0003_filtrelibakim_periyodik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PERIYODIK_TARIHI', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('PERSONEL_ADI', models.CharField(max_length=50, verbose_name='Personel Tam Adı')),
                ('FIRMA', models.CharField(max_length=100, verbose_name='Firma ')),
                ('MESLEK', models.CharField(choices=[('Elektrik', 'Elektrik'), ('Motor', 'Motor'), ('İdari', 'İdari'), ('Diğer', 'Diğer')], max_length=50, verbose_name='Meslek ')),
                ('TELEFON', models.CharField(max_length=100, verbose_name='Telefon No ')),
                ('ACIKLAMA', models.TextField(blank=True, verbose_name='Açıklama  ')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan ')),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personeller',
            },
        ),
        migrations.AlterField(
            model_name='arizalar',
            name='PERSONEL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jenerator.personel', verbose_name='Personel '),
        ),
        migrations.AlterField(
            model_name='filtrelibakim',
            name='PERSONEL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jenerator.personel', verbose_name='Personel '),
        ),
        migrations.AlterField(
            model_name='periyodik',
            name='PERSONEL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jenerator.personel', verbose_name='Personel '),
        ),
    ]
