# Generated by Django 3.2.9 on 2021-12-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenerator', '0004_auto_20211224_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='TCKIMLIK',
            field=models.IntegerField(blank=True, null=True, verbose_name='TC Kimlik No '),
        ),
    ]
