# Generated by Django 3.2.9 on 2021-12-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenerator', '0005_personel_tckimlik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='TCKIMLIK',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TC Kimlik No '),
        ),
    ]
