# Generated by Django 3.2.9 on 2021-12-27 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('katodik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OLUSTURMA_TARIHI', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('PANO_ADI', models.CharField(max_length=50, verbose_name='Pano Adı: ')),
                ('PANO_TIPI', models.CharField(choices=[('PIC', 'PIC'), ('PLC', 'PLC'), ('DSPIC', 'DSPIC'), ('Diğer', 'Diğer')], max_length=50, verbose_name='Pano Tipi  ')),
                ('PANO_MARKA', models.CharField(max_length=50, verbose_name='Pano Marka Modeli  ')),
                ('DEVREYE_ALMA_TARIHI', models.DateField(verbose_name='Devreye Alma Tarihi')),
                ('MODEM', models.CharField(max_length=50, verbose_name='Modem Marka Model: ')),
                ('IP', models.CharField(max_length=50, verbose_name='IP: ')),
                ('KONUM', models.CharField(max_length=50, verbose_name='Konumu ')),
                ('ACIKLAMA', models.TextField(blank=True, null=True, verbose_name='Açıklama ')),
                ('HAT', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='katodik.hatlar', verbose_name='Koruduğu Hat ')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan ')),
            ],
            options={
                'verbose_name': 'Pano',
                'verbose_name_plural': 'Panolar',
            },
        ),
    ]
